title: Prisma de luz
author: Caneluz
email: cop.candela@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Porque este ser humano llamado Cande necesitaba juntar sus tomas de notas en un lugar menos 
  flotante que las redes sociales y un blog parecía ese buen depósito. 
  Che, estás ante algo parecido a un diario. 
    Yo soy una carta abierta, tratá estos pensamientos con cuidado. 
    Todavía se siguen desarrollando.



# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
